# Lily hello world configuration file

# The address for the server to bind.
# Default: 127.0.0.1
bind: 0.0.0.0

# Port for the server to listen for.
# Default: 5555
port: 8000

# Here you can register the middleware you want to use in your app.
# To the name here to be recognised by the middleware installer it must be registered
# and for that it have to be imported somewhere in your project or manually resisted
# using the lily.RegisterMiddleware function.
middlewares:
  - accesslog

# Loggers
# More than one logger can be deployed. The names of the loggers can be any string as long
# as they don't repeat.
# Lily log implementation is on top of go-logging. Details on the layout format can be found
# here - http://github.com/op/go-logging.
loggers:
  main:
    type:   console
    layout: "%{level:.4s} %{time:2006-01-02 15:04:05.000} %{shortfile} %{message}"
    level:  debug
  file:
    type:   file
    path:   /tmp/linda.log
    layout: "%{time:2006-01-02 15:04:05.000} %{level:.4s} %{shortfile} %{message}"
    level:  info

# The access log is only one and can be showed in the console or in file. In case of
# using file an extra parameter for path is in order.
accesslog:
  type: console
